* The covers of the books of Sri Chinmoy

This repository contains the the original first-edition covers of the books by [[http://www.srichinmoy.org][Sri Chinmoy]].


The /Sri Chinmoy book covers/ are hosted at https://github.com/vasudevaserver/sri-chinmoy-book-covers

The repository is published in different forms at different public sites.

One such site is the [[http://www.srichinmoylibrary.com][Sri Chinmoy Library]].


** Licence

Sri Chinmoy's express wish was to release all of his works under conditions satisfactorily expressed by the following licence:

/Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)/

In short, you are free to share, copy and redistribute the material in any medium or format under the following terms:

- *Attribution* — You must give appropriate credit, provide a link to the licence, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licenser endorses you or your use of the material.
- *NonCommercial* — You may not use the material for commercial purposes.
- *NoDerivatives* — If you remix, transform, or build upon the material, you may not distribute the modified material.
- *No additional restrictions* — You may not apply legal terms or technological measures that legally restrict others from doing anything the licence permits. 

The licenser cannot revoke these freedoms as long as you follow the licence terms.

More information: [[https://creativecommons.org/licenses/by-nc-nd/4.0/][Creative Commons BY-NC-ND 4.0]]
